spring.application.name=scanner

gemini.api.key = ${GEMINI_API_KEY}

gemini.api.url = https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

google.auth.url = https://oauth2.googleapis.com/token

google.userInfo.url = https://oauth2.googleapis.com/tokeninfo

google.auth.clientID = ${GOOGLE_CLIENT_ID}

google.auth.clientSecret ={GOOGLE_CLIENT_SECRET}